### ISSUE TITLE
rust: to short buffers result in panic 

### ISSUE THREAD

**Issue by crop2000** [grame-cncm/faust#1081]
The rust code that is currently generated panics if the provided buffers are to short.
Is this really what we want?
Or would it be better if we iterate over the buffer as it is provided, and stop after N steps or end of buffer?
i created a example [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f91d55fb0bb2d9b3a2f098e8b933964c).
i suggest to change:
`let inputs0 = inputs0[..count as usize].iter();`
to
`let inputs0 = inputs0.iter().take(count);`

@obsoleszenz
@bluenote10

**Comment by sletz** [comment]
In general, we want the fastest possible code, to avoiding runtime checks as much as possible. I understand the desire to be safe when targeting Rust,  but how can the "end of buffer"  be checked in an efficient manner ?

**Comment by crop2000** [comment]
This `inputs0[..count]` we create a slice, which is a struct with a pointer and a length.
I expected that `take` is more efficient then creating a slice.
To reason about the impact of a iterator is a bit more complicated because i don't know how it is implemented and optimized.
I created a simple [example](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=f91d55fb0bb2d9b3a2f098e8b933964c) and looked at the created assembly code. in the case of using a slice a section for the panic is created and there are some other extra operations.

Initially i thought using take allows us to simplify the generated code, obviously one shouldn't generate a less performant method. I will have a look at how i can create a benchmark. 

But the question here is foremost the following: do we appreciate the panic or would a silent use of a too short buffer be OK?

**Comment by bluenote10** [comment]
In my opinion, it is a _precondition_ of `compute` that the buffer has a sufficient size, so a panic feels right.

Looking at it from the other perspective: It is a bug, if someone calls `compute` with a `count` that is larger than the buffer they provide to it. A bug like that should not silently be accepted.

> For using iterators over loops in the generated rust code, I think we would need to benchmark this. 

We already did quite some benchmarking on this. The initial implementation of the Rust code generation was using buffer accessed like `buffer[index]`. We noticed that the generated assembly did not produce vectorized code in these cases, and the Rust was slower in these [Faust Rust vs C++ benchmarks](https://github.com/bluenote10/RustFaustExperiments/tree/master/Benchmarks). The trick to get Rust to emit vectorized assembly was to switch from indexed access to using zipped iterators, because they allow Rust to optimize away the bounds checks. The switch to zipped iterators gave the performance a huge boost. You can probably find related discussions here in the PR / ticket / git history.

**Comment by crop2000** [comment]
I got the idea to use take as it could be added after the zipped iters.

**Comment by crop2000** [comment]
the current implementation seem to be the most performant.
