### ISSUE TITLE
world target installs ELF files to "architecture-independent program data folder"

### ISSUE THREAD

**Issue by dvzrv** [grame-cncm/faust#123]
When building faust with the 'world' target, it installs some ELF files to the wrong location.
[namcap](https://wiki.archlinux.org/index.php/Namcap), the [pacman](https://wiki.archlinux.org/index.php/Pacman) package and buildscript check tool complains about this, when building in a clean chroot:

```
faust E: ELF file ('usr/share/faust/osclib/libOSCFaust.so.0.95') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/libOSCFaust.so.0.95') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/OSCControler.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/threads/winthreads_impl.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/threads/pthreads_impl.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/msg/Message.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/osc/OSCSetup.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/osc/OSCStream.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/osc/OSCListener.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/osc/OSCIO.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/osc/OSCAddress.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/nodes/FaustFactory.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/nodes/RootNode.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/nodes/FaustNode.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/nodes/MessageDriven.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/lib/OSCFError.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/faust/src/lib/OSCRegexp.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/oscpack/osc/OscReceivedElements.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/oscpack/osc/OscOutboundPacketStream.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/oscpack/osc/OscTypes.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/oscpack/osc/OscPrintReceivedElements.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/oscpack/ip/IpEndpointName.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/oscpack/ip/posix/NetworkingUtils.o') outside of a valid path.
faust E: ELF file ('usr/share/faust/osclib/oscpack/ip/posix/UdpSocket.o') outside of a valid path.

```
`/usr/share/faust` is not the correct location for libraries (but `/usr/lib/faust` would be)!

**Comment by agraef** [comment]
As @dvzrv correctly pointed out, /usr/share is for platform-independent stuff *only*. Any kind of platform-dependent binaries are supposed to go into /usr/lib. Unix/Posix file system standards are there for a reason and it should be really easy for someone in the know to adhere to them.

This *is* a major headache for us package maintainers and make our lives miserable, so this really needs to be fixed. Point in case, debuild, when building the faust package, spits out a gazillion of lint errors and warnings related to this as well, so I always have to go digging through all this mud to make sure that the package was built correctly in spite of all the messages.

We could do a PR which moves all this stuff to the correct directories, but that will surely break the related scripts (faust2api et al?), so this needs to be done by someone who actually knows where all these binaries are needed.  @rmichon? Yeah, I know you're terribly busy right now, but maybe you can take a look after your defense and the party? ;-)

**Comment by sletz** [comment]
I can have a look.

**Comment by sletz** [comment]
@dvzrv : are you building latest master-dev git branch? (I don't see osclib stuff going to  usr/share/faust/)

**Comment by dvzrv** [comment]
@sletz Sorry, should've mentioned: This is the build for 2.5.10 to prepare for inclusion in the Arch Linux [community] repository.
I'll see what the devtools have to say about the -git package @agraef is supplying in the AUR.

**Comment by sletz** [comment]
Can you check again with master-dev git version ? (we plan to do a 2.5.17 release based on it soon...)

**Comment by dvzrv** [comment]
@sletz Just did (using @agraef 's [package in the AUR](https://aur.archlinux.org/packages/faust-git/), which is based on the latest commit from master-dev).
It has the same issue as the release, that I built.

**Comment by dvzrv** [comment]
The relevant line in the Makefile seems to be [this](https://github.com/grame-cncm/faust/blob/master-dev/Makefile#L192).

**Comment by dvzrv** [comment]
In case, that this is any help, [here's the build script for the (stable) package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=faust).

**Comment by sletz** [comment]
"In case, that this is any help, here's the build script for the (stable) package." ==> could you possibly create a PR for master-dev starting from it ?

**Comment by agraef** [comment]
@sletz Sorry for the confusion, we do a `make world` in the Arch package, which includes osclib.

In any case, this *has* to be fixed by someone who knows what these binaries are good for. As I said, if we just move the stuff into /usr/lib/faust then it's bound to break some architectures and tool scripts.

**Comment by sletz** [comment]
*I* am supposed to know that... at least as well as @rmichon ((-;

**Comment by agraef** [comment]
@sletz Ok then, get working. :)

No, seriously, if you tell me which architectures/tools are affected by this then I can probably take care of it (not before next week, though, I'm snowed under with work right now).

To be clear, here are the binary files this is all about:

~~~
/usr/share/faust/libsndfile.a
/usr/share/faust/osclib/faust/src/threads/winthreads_impl.o
/usr/share/faust/osclib/faust/src/threads/pthreads_impl.o
/usr/share/faust/osclib/faust/src/msg/Message.o
/usr/share/faust/osclib/faust/src/osc/OSCIO.o
/usr/share/faust/osclib/faust/src/osc/OSCListener.o
/usr/share/faust/osclib/faust/src/osc/OSCStream.o
/usr/share/faust/osclib/faust/src/osc/OSCSetup.o
/usr/share/faust/osclib/faust/src/osc/OSCAddress.o
/usr/share/faust/osclib/faust/src/nodes/FaustFactory.o
/usr/share/faust/osclib/faust/src/nodes/FaustNode.o
/usr/share/faust/osclib/faust/src/nodes/MessageDriven.o
/usr/share/faust/osclib/faust/src/nodes/RootNode.o
/usr/share/faust/osclib/faust/src/lib/OSCRegexp.o
/usr/share/faust/osclib/faust/src/lib/OSCFError.o
/usr/share/faust/osclib/faust/src/OSCControler.o
/usr/share/faust/osclib/faust/libOSCFaust.so.0.95
/usr/share/faust/osclib/faust/libOSCFaust.a
/usr/share/faust/osclib/libOSCFaust.so.0.95
/usr/share/faust/osclib/libOSCFaust.a
/usr/share/faust/osclib/liboscpack.a
/usr/share/faust/osclib/libOSCFaust.so
/usr/share/faust/osclib/oscpack/osc/OscReceivedElements.o
/usr/share/faust/osclib/oscpack/osc/OscPrintReceivedElements.o
/usr/share/faust/osclib/oscpack/osc/OscOutboundPacketStream.o
/usr/share/faust/osclib/oscpack/osc/OscTypes.o
/usr/share/faust/osclib/oscpack/ip/IpEndpointName.o
/usr/share/faust/osclib/oscpack/ip/posix/NetworkingUtils.o
/usr/share/faust/osclib/oscpack/ip/posix/UdpSocket.o
/usr/share/faust/osclib/oscpack/liboscpack.a
/usr/share/faust/osclib/libOSCFaust.so.0
~~~

As you can see, these all belong to osclib except the libsndfile archive. They all get installed in the `make install` targets somewhere.

/usr/share/faust/libsndfile.a is a Mach-O universal binary. Is this being used with the iOS architectures? I've never used these so I'm just guessing there. But it doesn't really matter, it's a Mac-format binary, so it shouldn't go into /usr/share, period.

The osclib stuff apparently gets installed at faust/Makefile:192:

~~~
cp -r architecture/osclib $(prefix)/share/faust
~~~

I'm not sure what good it does to install the osclib **sources** along with the compiled binaries under /usr/share/faust, do you have an idea? Note that the library binaries *are* in fact installed in their proper location directly under /usr/lib a bit further down in the Makefile, so that the linker will find them if needed (line 227):

~~~
	([ -e architecture/httpdlib/libHTTPDFaust.a ] && cp architecture/httpdlib/libHTTPDFaust.a $(prefix)/lib/) || echo libHTTPDFaust.a not available
	([ -e architecture/httpdlib/libHTTPDFaust.$(LIB_EXT) ] && cp architecture/httpdlib/libHTTPDFaust.$(LIB_EXT) $(prefix)/lib/) || echo libHTTPDFaust.$(LIB_EXT) not available
~~~

So why are these also installed in /usr/share/faust/osclib (where they don't belong)? And why are the sources of osclib installed there as well (these don't hurt anyone, I'm just wondering).

**Comment by sletz** [comment]
osclib sources are needed by the `faust2ios` script. The complete osclib folder is currently simply copied, which is not really correct yes. Copying the .h and .cpp would be the correct way.

**Comment by agraef** [comment]
BTW, @sletz, Makefile:192 was in fact committed by you, the original commit was rev. 16b9f60cc. So I hope that you still remember what you did there. ;-) Apparently the intention orginally was to provide the osclib sources in the installed package somewhere, is that right? Then maybe we can just augment Makefile:192 so that it removes all the .o, .so and .a's in the target directory after copying it over?

**Comment by agraef** [comment]
Oops sorry, our comments crossed. :) Ok, that should be clear now, I can take care of fixing that.

But what about the Mach-O libsndfile.a?

**Comment by sletz** [comment]
I'me on that right now... stay tuned!

**Comment by agraef** [comment]
Ok, thanks. :) Here's some more info I could gather grepping the sources. libsndfile.a is referenced in sound2faust/Makefile (but that reference seems irrelevant, it tries to link against /usr/local/lib/libsndfile.a there), architecture/iOS/iOS.xcodeproj/project.pbxproject (that one seems to be the relevant one) and debian/rules (which is my Debian packaging stuff, where I reference the file to silence debuild's warnings).

So I'd say that architecture/iOS/iOS.xcodeproj/project.pbxproject just needs to be modified so that it references /usr/local/lib/faust/libsndfile.a instead of /usr/local/share/faust/libsndfile.a, and make sure in the global Makefile that (/usr/local/lib/faust gets created and) libsndfile.a gets moved over from /usr/share/faust to /usr/lib/faust after installing the stuff in architecture. N'est-ce pas?

**Comment by sletz** [comment]
fix here : https://github.com/grame-cncm/faust/commit/0ab2d04e4d03893be0cf8dd324deb1793e22df9e

**Comment by sletz** [comment]
Second try : https://github.com/grame-cncm/faust/commit/79fed093a00bb8908634eb1bcc15907c31107fd6

**Comment by agraef** [comment]
Perfect, thanks a bunch! :) @dvzrv, the messages that you reported are all gone now if I build faust-git from latest git now, so I'm closing this issue.

**Comment by rmichon** [comment]
Sorry guys, just saw your thread. I'm insanely busy these days and I really don't have time to look at this kind of things if I actually want to sleep at night haha. Things will be better for me after the first half of February, but for now I'm running the last mile of my PhD marathon ;).

**Comment by agraef** [comment]
@rmichon it's all good already, @sletz already sorted it out. Sorry for calling on you, best wishes for the PhD last inches. :)

**Comment by rmichon** [comment]
Cheers! ;)
