### ISSUE TITLE
faust2jackconsole : "unrecognized option --group"

### ISSUE THREAD

**Issue by mephistopheles-8** [grame-cncm/faust#262]
It seems that the option `--group 0` results in an error message, "unrecognized option --group" for applications built with `faust2jackconsole`.  I think this is an issue in `gui/console.h`.

**Comment by sletz** [comment]
This should be fixed in https://github.com/grame-cncm/faust/commit/063efdbb0401cd248b3c174cdf4cfb19465a9c6f

A new `--control `parameter is now available in some of `faust2xx` scripts. So you'll have to to something like:

`faust2jaqt -midi -nvoices 8 -osc clarinetMIDI.dsp `

then `./clarinetMIDI --group 0 --control 0`

All polyphonic voices are always "on" and can be individually controlled with OSC messages.

**Comment by mephistopheles-8** [comment]
That seems to have fixed the issue -- thanks!
