### ISSUE TITLE
Include submodules in an asset tarball on each release

### ISSUE THREAD

**Issue by dvzrv** [grame-cncm/faust#276]
The current (automatic) source tarball of 2.14.4 doesn't include the submodule for the libraries.

Please add an asset tarball with the submodules included of the form `faust-$version.tar.gz` consistently (also for upcoming releases) during release, as it was done for the releases before.

This is required for packaging downstream. Thanks!

**Comment by umlaeute** [comment]
Debian is approaching it's freeze for buster, so i would really love this to be fixed.

@sletz if you don't intend to do it within the next hours/few days, please leave me a note (so I can fire up my workarounds)

**Comment by sletz** [comment]
We'll has to do a new release, but it will take more than a few hours.

**Comment by umlaeute** [comment]
?

for the issue at hand, it would be enough to just add another `asset` to the already existing [2.4.14 release](https://github.com/grame-cncm/faust/releases/tag/2.14.4).

**Comment by sletz** [comment]
2.14.4 is broken in different manners... We'll do a new release, probably doing a "rc" serie to get some feedback first

**Comment by umlaeute** [comment]
ok.

FYI, the Debian packages in *Debian/testing* are currently 2.14.4, and Debian is [rapidly approaching *freeze*](https://release.debian.org/buster/freeze_policy.html).
I'd prefer to not ship a broken faust with the next Debian release.

**Comment by sletz** [comment]
Do not package the 2.14.4, it is broken.

**Comment by umlaeute** [comment]
here's the facts:

- 2.14.4 is already [packaged and included](https://tracker.debian.org/pkg/faust) in Debian/testing.
- if we (I) don't do anything about it in the *next few days*, it will be shipped with the next Debian release (Buster).

if we are (I am) to do something about it, I need to know *what*.
as in:
- what is *your* timeline for a non-broken release of faust?
- if you are pretty sure that you cannot come up with a non-broken release of faust within the next days, what it the version of faust that *should* be packaged instead?


it is really, **really** complicated to get packages updated after a Debian release. Esp. if they are somewhat specialized.

**Comment by sletz** [comment]
What I can say:
- we certainly have progress to make on our release strategy and more robust tools to deploy, but:
- published Faust 2.14.4 and FaustLive 2.5.0 have a dependency issue. FL 2.5.0 cannot be compiled with Faust 2.14.4.  If Faust 2.14.4 is released in next Debian, then users will possibly have this issue. What to do with that?
- we have several issues to fix before releasing a new Faust version. I cannot say more on the timing.
- we want to make a release of Faust *and* a release of FL that are compatible
- moreover I see a 2.13.14 stuff on the https://tracker.debian.org/pkg/faust ? What that. 2.13.13 has never been on official release.

**Comment by umlaeute** [comment]
thanks for your explanation.

the ` faust 2.13.14~git20181219.1.cd34eccb` as shown on https://tracker.debian.org/pkg/faust, was an intermediate package on my side, solely because:

the last faust release (iirc, 2.5.23) would simply not compile at all with the LLVM toolchain in current Debian. 

anticipating a proper release before Debian freeze, i decided to package a git-snapshot, to clear things out before the Debian freeze (Debian freeze is not the right time to discover that dependencies are missing, or that the package fails to build on multiple architectures, or what not).

in retrospect, this was probably a pre-mature decision. the alternative would have been to keep shipping `faust-0.9.95` or to completely remove faust from the Debian archives.
neither option sounded very appealing, and i remember promising to update the faust packages at the LAC dinner a while ago, so i wanted to ship a new package in the next Debian release...

anyhow, the harm is now done, and I can only apologize for it (and hope we can find a solution that is satisfactory for all of us)

**Comment by dvzrv** [comment]
@sletz thanks for including this in 2.15.10 again. Can I assume, that this release is packagable?

**Comment by sletz** [comment]
It is still a prerelease, we still have some issues to fix and want to wait some more days.  We'll announce when its ready.

**Comment by dvzrv** [comment]
Alright, thanks! :)
