### ISSUE TITLE
 Trouble with "toy.dsp" compiling to Android

### ISSUE THREAD

**Issue by sletz** [grame-cncm/faust#320]
I'm taking a Faust class through Kadenze.  Trying to get the "toy.dsp" running.  I got the code exported as source/smartkeyb-android and as able to build it in Android Studio on Windows 10.
It uploads to the phone but then I get:

Unfortunately, untitled has stopped running.

If you try it again, it says:

untitled keeps stopping

It does this on my LG Sylo VS835 with Android 7.0, as well as an older Samsung Galaxy Tab with 4.4.2.

The sample "Hello World" application works.

Thanks,

GW

**Comment by Digital-Larry** [comment]
Update, toy.dsp works fine exported as android/android to Android 4.4.2.  I believe the issue may be the result of the instructions in the Kadenze coursework suggesting that toy.dsp be compiled as "smartkeyb".  Now if there is some valid scenario where this code is supposed to be compatible with compilation for the "smartkeyb" target, then there really is a problem with the code.  Otherwise I'd say there's a problem with the Kadenze coursework instructions.  Either that or there's some obscure reason you'd export to smartkeyb but you don't really want to leverage the smartkeyb interface.

To wit:
"Use the looper/granulator from Session 4 to make a mobile app (iOS or Android) with faust2smartkeyb. This app should work in a similar way as toy.dsp (i.e., its interface shouldn't be an actual keyboard and sound should be computed when the app is launched)."
