### ISSUE TITLE
Usage of undefined jack function (jack_midi_reset_buffer)

### ISSUE THREAD

**Issue by sezna** [grame-cncm/faust#339]
When building any Faust program to Jack with faust2jack, faust2jaqt, or any of the other jack targets, the following error is generated:
```
test_tmp.cpp:7512:17: error: use of undeclared identifier 'jack_midi_reset_buffer'; did you mean 'jack_midi_clear_buffer'?
                jack_midi_reset_buffer(port_buf_out);
                ^~~~~~~~~~~~~~~~~~~~~~
                jack_midi_clear_buffer
/usr/local/include/jack/midiport.h:86:1: note: 'jack_midi_clear_buffer' declared here
jack_midi_clear_buffer(void           *port_buffer) JACK_OPTIONAL_WEAK_EXPORT;
^
1 error generated.
make: *** [test_tmp.o] Error 1
```

Was there a function name change in between versions of jack?

I am on Mac OS Mojave 10.14.5 with the latest Faust and I brew install'd Jack yesterday, so it should also be the latest.

**Comment by sletz** [comment]
This `jack_midi_reset_buffer` function was added when I was experimenting with JACK some years yeas, but was not added in the official AJCK API. Since it is not used in "standard" use-cases, I just removed it in master-dev branch (in https://github.com/grame-cncm/faust/commit/fc6df125f10e78e1b6aa14bae3a04bcf1c86ae5a)
Can you test and report? Thanks.

**Comment by sezna** [comment]
It is working on master-dev now. Thanks! I appreciate your work on this project.

**Comment by sezna** [comment]
Realized I probably shouldn't close this until it gets merged into master...
