### ISSUE TITLE
faust2unity GUI bug

### ISSUE THREAD

**Issue by Rickr922** [grame-cncm/faust#360]
When trying to use a plug in for Unity I am experiencing a weird issue. When attacing the C# code to an audio source the inspector does not show me the contents properly. The "Initialization" button does not work and it overlaps with the rest of the content of the inspector, as you can see in the image

![faust2unitybug](https://user-images.githubusercontent.com/56834876/68692843-7bd41d80-0576-11ea-88a8-a7632276eee2.png)

Let me know if I can do anything for help you better debug this problem.

**Comment by sletz** [comment]
Can you send or paste the Faust DSP code?

**Comment by Rickr922** [comment]
Thanks for fast answer!
This is the code:

import("stdfaust.lib");
freq = hslider("freq", 200, 200, 2000, 0.1);
gain = hslider("gain", 0.0, 0.0, 1.0, 0.01);
process = os.osc(freq) * gain<:_, _;

It's just a simple sinewave generator trial for testing out how Unity compatibility works, I exported it using the web based ide

**Comment by sletz** [comment]
Sorry I am a very rare Unity user: can you explain again step by step how to obtain the window you are showing ? Thanks.

**Comment by Rickr922** [comment]
Sure, we found the bug in a very early stage of the development of the project, so it needs just a few steps in order to trigger it.

- Create a new project using Unity Hub (3D project)
- Drag and drop the .unitypackage file created with Faust into Assets folder (bottom left), it'll ask to
   choose which file to import, import everything with default settings
- Right click on main camera > 3D Object > Cube (or any other object)
- Select the cube in order to see its properties on the inspector on the right
- Go into Scripts folder (bottom left), there should be two scripts, drag and drop the FaustPlugin script 
   into the cube inspector, between two "tabs", then you should see the bug in the inspector.

I hope it was clear, I'm not a frequent Unity user too, but I'm working with a Unity developer for a university project, so I am not familiar with Unity naming.

Thanks for the help.

**Comment by tinpark** [comment]
Hi, I had the same problem until I realised that I wasn't including a properly compiled version of the plugin for my OS. Using the commandline version of Faust, I ran `faust2unity -osx -source -unpacked testForUnity.dsp` in my working directory and it built a OSX .bundle. Place that .bundle inside plugins inside Unity and the C# should work... Hope that helps and doesn't come across as total nonsense to you. Obviously if you're on windows, then you need to compile a Windows version of the plugin for it to behave in the windows version of Unity.

**Comment by tinpark** [comment]
In fact, I have this same issue as you Rickr922 since trying to use a more uptodate version of faust; 2.20: faust2unity refuses to compile a working .bundle. Faust 2.14 works fine. The bundle imports fine, but won't expose the gui as described above. Wondering if anyone is looking into this at present as I really want to try some of the more recent Faust DSP physical models such as those that rely on Route, inside Unity and can't do this at present. Here are the errors that Unity spits out 

`
System.Number.StringToNumber (System.String str, System.Globalization.NumberStyles options, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Number.ParseInt32 (System.String s, System.Globalization.NumberStyles style, System.Globalization.NumberFormatInfo info) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Int32.Parse (System.String s, System.IFormatProvider provider) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Convert.ToInt32 (System.String value) (at <567df3e0919241ba98db88bec4c6696f>:0)
FaustUtilities_fluteSound.FaustUI.fJSONParser (System.String& fJSON, FaustUtilities_fluteSound.FaustUI& faustUI) (at Assets/Scripts/FaustUtilities_fluteSound.cs:366)
FaustUtilities_fluteSound.FaustPlugin_Editor.OnEnable () (at Assets/Scripts/FaustUtilities_fluteSound.cs:29)`

Thanks in advance of any time anyone puts into this.
