### ISSUE TITLE
Windows version for mesh2faust

### ISSUE THREAD

**Issue by nesdnuma** [grame-cncm/faust#369]
Hello,

A Windows version of mesh2faust would be nice. People around Faust do not seem to like Windows but many people can't avoid using it (for instance because their students use that system).

Best regards,

**Comment by rmichon** [comment]
Haha, the good old Windows question ;). The toolchain behind mesh2faust was really designed for Unix systems which is why there doesn't exist a Windows version. Developing a Windows version of mesh2faust would take a lot of time which we currently don't have. The reason why Windows is not well supported in the Faust world is because the dev chain on this platform is completely different than the one on Linus and MacOS which are very similar. Maintaining the whole Faust ecosystem is already very time consuming and we couldn't really afford to add Windows to this load, especially since a large portion of the people in the audio world use Linux or MacOS.

**Comment by nesdnuma** [comment]
I undestand. :-(
