### ISSUE TITLE
AR envelope behaves unexpectedly since recent change

### ISSUE THREAD

**Issue by topisani** [grame-cncm/faust#55]
Ever since https://github.com/grame-cncm/faust/commit/1f116ca7889f5cadc73e6b6b5355313be4b77430 `en.ar` behaves what i believe to be unintuitively

this change means that the envelope will go to 0 when the trigger goes to 0. This means, that to use the envelope, you have to keep the trigger at 1 for at least `attTime + relTime`

I have absolutely no idea why this could be wanted, but if it's intentional, don't mind me.

**Comment by rmichon** [comment]
Indeed... Thanks for reporting that. I fixed the problem [here](https://github.com/grame-cncm/faust/commit/245c2f8da4eb3f5d1f3dd8e3d94b3bd3071806e8). This is due to the implementation of countup used in the envelope generator that doesn't allow to set an init value. We should probably add this init parameter to countup and countdown, but it might break some people's code so for now I just created a local version in en.ar.

**Comment by sletz** [comment]
the maxim count value ==> the **maximum** count value ??

**Comment by rmichon** [comment]
Woops :). Fixed [here](https://github.com/grame-cncm/faust/commit/9dfb98cfd0bdaca3a6b6ef02b9f5153a8437439f)

**Comment by topisani** [comment]
Amazing! thanks, just out of interest, what was the idea of the change in the first place? how does `en.ar` work differently now from before the original commit that introduced this problem?

**Comment by rmichon** [comment]
Excellent question ;). The old version worked fine except that it would trigger a note when the program was launched which was kind of annoying haha.

**Comment by topisani** [comment]
Ah! yup i definately experienced that, i thought it was my faustwrappers fault. Well fixing that is awesome, i had 24 drum voices and a metronome click all at once when i launched it :stuck_out_tongue:
