### ISSUE TITLE
explicit variable-name separator required

### ISSUE THREAD

**Issue by x42** [grame-cncm/faust#787]
It seems impossible to separate 2 variable names using an underscore.

Say I have 2 variables `foo(i,j) = vbargraph("Foo [symbol:foo_%i_%j]")`
In this case the first is interpreted as variable `i_` even though that is not declared in the context.

I have tried bash like syntax `%{i}` and GNU style `%(i)` to no avail.

https://faustdoc.grame.fr/manual/syntax/#variable-parts-of-a-label  should document valid characters to use as variable names as listed in https://github.com/grame-cncm/faust/blob/13def69f21dd0cede393c13dcaf1a6fe7ef7f439/compiler/evaluate/eval.cpp#L794-L797

**Comment by orlarey** [comment]
You can't because underscore '_' is not a separator. It is part of the
allowed characters for identifiers. Therefore by writing "...%i_...." you
create a two-character identifier. Only one-character identifiers are
allowed in this context.

Le lun. 22 août 2022 à 20:27, Robin Gareus ***@***.***> a
écrit :

**Comment by sletz** [comment]
@orlarey I guess we should precisely document what characters are allowed 
somewhere here  https://faustdoc.grame.fr/manual/syntax/#variable-parts-of-a-label ?

**Comment by x42** [comment]
Follow up from the downstream project:


>    "....%i,....".

Sadly that won't work here. The generated **symbol** name is used in C/C++ GUI code and needs to be a valid C variable name. commas are not allowed there. Here we would like  "`meter_%b_$c`" to evaluate to  "`meter_2_3`"


@falktx mentioned

> One ugly but possible solution is using $ as character separator.
It is allowed in both GCC and MSVC, see https://stackoverflow.com/questions/7926394/dollar-sign-in-variable-name
And per C++11 onwards we are allowed to use more than just a-zA-Z0-9_ chars.

**Comment by falkTX** [comment]
Note that C++11 officially allows a few unicode characters as symbol names, which does not include $.

The best approach here would be for faust to support a variable start and end dedicated character, taking inspiration from bash being `%{i}` would be best. That way `%{i}_%{j}` would be allowed and work nicely.

**Comment by orlarey** [comment]
Right. We just extended the syntax for variables in labels (faust 2.46.0)
so that we can also write :

foo(i,j) = vbargraph("Foo [symbol:foo _%{i} _%{j}]", 0, 100);
process = foo(3,5);


when we need to better delimit the identifiers...

Le lun. 22 août 2022 à 23:28, Filipe Coelho ***@***.***> a
écrit :

**Comment by x42** [comment]
Brilliant! Amazingly fast response, thank you!

PS. Should I close this ticket, or are you going to do that when  2.46.0 is released?

**Comment by sletz** [comment]
Documentation updated: https://faustdoc.grame.fr/manual/syntax/#variable-parts-of-a-label

**Comment by orlarey** [comment]
It was not heavily tested, but I think you can close the ticket.

Le mar. 23 août 2022 à 14:58, Robin Gareus ***@***.***> a
écrit :
