### ISSUE TITLE
Wrong order of UI elements

### ISSUE THREAD

**Issue by mryndzionek** [grame-cncm/faust#873]
This:
```
process = par(i, 12, checkbox("v:Drum kit/h:[0]kick/%i"));
```
produces:
![xxx](https://user-images.githubusercontent.com/786191/227520730-c28eb67d-49ab-4c7d-ac98-e2cafa85fddf.png)

10 and 11 are out of order. Labels are probably sorted alphabetically. Adding `[%i]` before `%i` doesn't change that.

**Comment by sletz** [comment]
The variable part can have an optional format digit. For example "Voice %2i" would indicate to use two digit when inserting the value of i in the string.

See: https://faustdoc.grame.fr/manual/syntax/#variable-parts-of-a-label

So fixed with: `process = par(i, 12, checkbox("v:Drum kit/h:[0]kick/%2i"));`
